#!/usr/bin/env bash
#Display infomation about the school.
if [ -e "school"]
then
	echo "school file exits"
	if [ -s "school"]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "school" ]
	then
		echo "school is a regular file"
else
	echo "school file does not exist"
fi
